name: .NET Core CI (Continuous Integration)

on:
  push:
    branches:
      - develop

jobs:

  BuildAndTestApplication:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x

      - name: Restore dependencies
        run: dotnet restore
      
      - name: Build application
        run: dotnet build --no-restore

      - name: Test application
        run: dotnet test --no-build --verbosity normal

  CreatePullRequest:
    needs: BuildAndTestApplication
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create pull request
        run: gh pr create -B main -H develop --title 'Merge Develop into Main' --body 'Created automatic Pull Request by Github action.'
        env:
            GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}